apiVersion: v1
kind: Service
metadata:
  name: service-12jgh
  namespace: kube-system
  labels:
    app: service-12jgh
spec:
  type: ClusterIP
  selector:
    app: service-12jgh
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-12jgh
  namespace: kube-system
  labels:
    app: service-12jgh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-12jgh
  template:
    metadata:
      labels:
        app: service-12jgh
    spec:
      containers:
        - name: service-12jgh-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env: []
      imagePullSecrets:
        - name: scoutflo-kalpesh-bhalekar-docker
